In [1]:
import numpy as np

In [52]:
lista = np.array([1,2,3,4,5]) # vetor
lista1 = np.array([[1,2],[2,3],[3,4],[4,5],[5,6]]) # matriz

In [53]:
print(lista)
print()
print(lista1)


[1 2 3 4 5]

[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]


In [60]:
lista1 * 2

array([[ 2,  4],
       [ 4,  6],
       [ 6,  8],
       [ 8, 10],
       [10, 12]])

In [54]:
print(lista)

[1 2 3 4 5]


In [55]:
import pandas as pd

In [56]:
pd.DataFrame(lista, columns=['coluna1'])

coluna1
0        1
1        2
2        3
3        4
4        5

In [57]:
pd.DataFrame(lista1, columns=['coluna1','coluna2'])

coluna1  coluna2
0        1        2
1        2        3
2        3        4
3        4        5
4        5        6